# Generated by Django 3.2.4 on 2021-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210713_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorUsername',
            field=models.CharField(default='', max_length=50),
        ),
    ]
