# Generated by Django 3.2.4 on 2021-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_authorusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
