# Generated by Django 3.2.4 on 2021-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(upload_to='static/imgs/'),
        ),
    ]
