# Generated by Django 3.2.4 on 2021-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('blog_sno', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('authorUsername', models.CharField(default='', max_length=50)),
                ('Timestamp', models.CharField(max_length=50)),
                ('report', models.TextField()),
            ],
        ),
    ]
