# Generated by Django 3.2.4 on 2021-07-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='authorUsername',
        ),
    ]
