# Generated by Django 3.2.4 on 2021-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rep_by',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
