# Generated by Django 3.2.4 on 2021-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('authorUsername', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
